NUMPY IN PYTHON

In [15]:
import numpy as np

In [16]:
arrays= np.array([1,2,3,4,5,6])

arrays

print(np.__version__)

1.25.2


In [17]:
arrays=arrays*2

arrays

array([ 2,  4,  6,  8, 10, 12])

In [18]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

array2.ndim

2

In [ ]:
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]],
                 [[1,2,3],[4,5,6],[7,8,9]]]) 

array3.shape
array3.ndim

3

In [ ]:
print(array3[0,0,1])

bignumber=array3[0,0,0]+array3[0,1,0]


print(bignumber)


2
5


In [30]:
array4=np.array([[['A','B','C'],['D','E','F']],
                 [['G','H','I'],['J','K','L']],
                 [['M','N','O'],['P','Q','R']]]) 

bignumber2=array4[0,0,0] + array4[0,1,0]+array4[1,0,2]

print(bignumber2)

ADI


ROW Slicing

In [41]:
slicing=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

# slicing[start:end:step]

print(slicing[0:3])
print("-"*50)
print(slicing[0:])
print("-"*50)
print(slicing[0:4:2])
print("-"*50)
print(slicing[: :2])

print(slicing[: :-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------------------------------------
[[ 1  2  3  4]
 [ 9 10 11 12]]
--------------------------------------------------
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


column selection

In [47]:
print(slicing[0,3])

print(slicing[:,0])

print("-"*30)

print(slicing[ : ,1:3])

4
[ 1  5  9 13]
------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
print(slicing[0:2,0:2]) 

[[1 2 3 4]
 [5 6 7 8]]


ARITHMATIC in numpy

In [52]:
#Scalar arithmatic

arrays= np.array([1,2,3,4,5,6])

print(arrays+1)
print(arrays-1)
print(arrays*2)
print(arrays/2)
print(arrays**2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[ 1  4  9 16 25 36]


In [58]:
#Vector arithmatic

print(np.sqrt(arrays))
print(np.floor(arrays))
print(np.pi)

print(np.pi * arrays **2)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[1. 2. 3. 4. 5. 6.]
3.141592653589793
[  3.14159265  12.56637061  28.27433388  50.26548246  78.53981634
 113.09733553]


ElementWise Arithmatic

In [64]:
arrays1= np.array([100,22,36,4,55,67])
arrays2= np.array([1,2,3,4,5,6])

print(arrays1 + arrays2)
print(arrays1 - arrays2)
print(arrays1 * arrays2)
print(arrays1 / arrays2)

[101  24  39   8  60  73]
[99 20 33  0 50 61]
[100  44 108  16 275 402]
[100.          11.          12.           1.          11.
  11.16666667]


In [67]:
#comparison operators

print(arrays1==100)
print(arrays1 >=60)
print(arrays1 <60)

arrays1[arrays1 <60]=0

print(arrays1)

[ True False False False False False]
[ True False False False False  True]
[False  True  True  True  True False]
[100   0   0   0   0  67]


BROADCASTING in numpy

In [ ]:
arrays1= np.array([1,2,3,4,5,6])
arrays2= np.array([[1],[2],[3],[4],[5],[6]])


print(arrays1*arrays2)



[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


AGGRIGATE Function

In [77]:
agg= np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(np.sum(agg))
print(np.min(agg))
print(np.argmin(agg))
print(np.max(agg))
print(np.argmax(agg))
print(np.mean(agg))
print(np.std(agg))
print(np.var(agg))

print(np.sum(agg,axis=0))
print(np.sum(agg,axis=1))

55
1
0
10
9
5.5
2.8722813232690143
8.25
[ 7  9 11 13 15]
[15 40]


Filtering in numpy

In [85]:
ages=np.array([[21,17,19,20,16,65],[39,22,15,99,18,19]])

underages=ages[ages<18]


print(underages)

overages=ages[(ages >18 )& (ages<70)]
overages2=ages[(ages >18 )| (ages<70)]
print(overages)
print(overages2)

even=ages[ages % 2==0]

print(even)


adults=np.where(ages >=18 , ages,0)

print(adults)

[17 16 15]
[21 19 20 65 39 22 19]
[21 17 19 20 16 65 39 22 15 99 18 19]
[20 16 22 18]
[[21  0 19 20  0 65]
 [39 22  0 99 18 19]]


random numbers

In [101]:
rng=np.random.default_rng()#seed=1

print(rng.integers(1,6)) 
print(rng.integers(low=1,high=100))
print(rng.integers(low=1,high=100,size=(2)))
print(rng.integers(low=1,high=100,size=(2,3)))


print(np.random.uniform(low=1,high=10))

#shuffeling

shu=np.array([1,2,3,4,5])
rng.shuffle(shu)
print(shu)

fruits=np.array(['apple','orang','banana','coconut'])

fruit=rng.choice(fruits)

print(fruit)


5
53
[59 44]
[[13 83 61]
 [ 5 18  9]]
9.695322955478995
[3 4 1 2 5]
banana
